---
- name: Initalize Project/ Integrate new Update
  hosts: dev
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: Create Project Directory
      ansible.builtin.file:
        path: "{{project_path}}"
        state: directory

    - name: Pull Code
      git:
        repo: "{{remote_repo}}"
        dest: "{{project_path}}"
        version: dev
        force: yes

    - name: Install npm dependencies from package.json
      npm:
        path: "{{project_path}}"
      environment:
        PATH: "{{ansible_env.PATH}}:{{nvm_path}}"

    - name: Create .env file
      copy:
        content: |
          JWT_SECRET=""
          SENDGRID_API_KEY= ''
        dest: "{{project_path}}/.env"
        force: false

    - name: Create .env.prod file
      copy:
        content: |
          DATABASE_URL=""
        dest: "{{project_path}}/.env.prod"
        force: false

    - name: Create .env.dev file
      copy:
        content: |
          DATABASE_URL=""
        dest: "{{project_path}}/.env.dev"
        force: false

    - name: deploy migrations with prisma
      command: "dotenv -e .env.dev npx prisma migrate deploy"
      args:
        chdir: "{{ project_path }}"
      register: prisma_result
      failed_when: prisma_result.rc != 0
      environment:
        PATH: "{{ansible_env.PATH}}:{{nvm_path}}"

    - name: log prisma result
      debug:
        msg: "{{prisma_result.stdout}}\n:{{prisma_result.stderr}}\n:{{prisma_result.rc}}"

    - name: start the application
      command: pm2 start ecosystem.config.js --only richmond-dev
      args:
        chdir: "{{ project_path }}"
      environment:
        PATH: "{{ansible_env.PATH}}:{{nvm_path}}"

